import os
import requests
from dotenv import load_dotenv

load_dotenv()


def search_with_subject_filters(query, subject_filters=None, max_results=40):
    """
    Search Google Books with subject filters and proper query construction.
    
    Args:
        query: The search term(s)
        subject_filters: List of subject filters (e.g., ["fiction", "romance"])
        max_results: Number of results to request (30-50 for candidates)
    
    Returns:
        List of normalized book dictionaries
    """
    api_key = os.getenv("GOOGLE_BOOKS_API_KEY", "")
    url = "https://www.googleapis.com/books/v1/volumes"
    
    try:
        # Build advanced query with subject filters
        query_parts = [f'"{query}"']  # Quote the main query for exact matching
        
        if subject_filters:
            # Add subject filters
            for subject in subject_filters:
                query_parts.append(f'subject:{subject}')
        
        full_query = " ".join(query_parts)
        
        print(f"[BookRetriever] Query: {full_query}")
        
        params = {
            "q": full_query,
            "maxResults": max_results,
            "printType": "books"
        }
        
        if api_key:
            params["key"] = api_key
        else:
            print("[BookRetriever] Warning: No API key. Rate limits may apply.")
        
        response = requests.get(url, params=params, timeout=15)
        response.raise_for_status()
        
        data = response.json()
        books = []
        
        for item in data.get("items", []):
            try:
                book = _normalize_volume(item.get("volumeInfo", {}))
                books.append(book)
            except Exception as e:
                print(f"[BookRetriever] Error normalizing item: {e}")
                continue
        
        print(f"[BookRetriever] Retrieved {len(books)} books for query: {query}")
        return books
    
    except Exception as e:
        print(f"[BookRetriever Error] {e}")
        return []


def search_by_title(title, max_results=10):
    """
    Search Google Books by exact book title.
    Used for BOOK_QUERY type.
    """
    return search_with_subject_filters(
        query=title,
        subject_filters=["fiction"],
        max_results=max_results
    )


def search_by_author(author, max_results=30):
    """
    Search Google Books by author name.
    Used for AUTHOR_QUERY type.
    """
    query = f'inauthor:"{author}"'
    api_key = os.getenv("GOOGLE_BOOKS_API_KEY", "")
    url = "https://www.googleapis.com/books/v1/volumes"
    
    try:
        params = {
            "q": query,
            "maxResults": max_results,
            "printType": "books"
        }
        
        if api_key:
            params["key"] = api_key
        
        response = requests.get(url, params=params, timeout=15)
        response.raise_for_status()
        
        data = response.json()
        books = []
        
        for item in data.get("items", []):
            try:
                book = _normalize_volume(item.get("volumeInfo", {}))
                books.append(book)
            except Exception as e:
                continue
        
        print(f"[BookRetriever] Retrieved {len(books)} books by author: {author}")
        return books
    
    except Exception as e:
        print(f"[BookRetriever Author Search Error] {e}")
        return []


def search_by_mood(search_terms, genres=None, max_results=50):
    """
    Search Google Books using mood/vibe search terms with subject filtering.
    Used for MOOD_QUERY type.
    
    Args:
        search_terms: List of search phrases (generated by Gemini)
        genres: List of genre subjects to filter by
        max_results: Number of results per search term
    
    Returns:
        Merged list of unique books from all search terms
    """
    if not genres:
        genres = ["fiction"]
    
    all_books = []
    seen_titles = set()
    
    for search_term in search_terms:
        print(f"[BookRetriever] Searching mood query: {search_term}")
        books = search_with_subject_filters(
            query=search_term,
            subject_filters=genres,
            max_results=max_results
        )
        
        for book in books:
            # Deduplicate by title
            title_key = book["title"].lower()
            if title_key not in seen_titles:
                all_books.append(book)
                seen_titles.add(title_key)
    
    print(f"[BookRetriever] Total unique books from mood search: {len(all_books)}")
    return all_books


def _normalize_volume(volume_info):
    """
    Convert Google Books volumeInfo to standard format.
    """
    images = volume_info.get("imageLinks", {})
    cover_url = images.get("thumbnail") or images.get("smallThumbnail") or ""
    pub_date = volume_info.get("publishedDate", "N/A")
    
    return {
        "title": volume_info.get("title", "Unknown Title"),
        "authors": volume_info.get("authors", ["Unknown Author"]),
        "description": volume_info.get("description", "No description available."),
        "categories": volume_info.get("categories", ["Uncategorized"]),
        "published_year": pub_date[:4] if len(pub_date) >= 4 else "N/A",
        "cover_image": cover_url,
        "page_count": volume_info.get("pageCount", 0),
        "publisher": volume_info.get("publisher", ""),
        "isbn": volume_info.get("industryIdentifiers", [{}])[0].get("identifier", "")
    }
